export const BCRYPT_ROUNDS = 12;

export const SECONDS_PER_MINUTE = 60;
export const MILLISECONDS_PER_SECOND = 1000;
export const MILLISECONDS_PER_MINUTE =
  SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;
export const MILLISECONDS_PER_HOUR = 60 * MILLISECONDS_PER_MINUTE;
export const MILLISECONDS_PER_DAY = 24 * MILLISECONDS_PER_HOUR;

export const MAX_UPLOAD_SIZE_BYTES = 10 * 1024 * 1024; // 10MB

export const MAX_FAILED_LOGIN_ATTEMPTS = 15;
export const LOGIN_LOCK_WINDOW_MS = 15 * MILLISECONDS_PER_MINUTE;
export const LOGIN_ATTEMPTS_CLEANUP_MS = MILLISECONDS_PER_DAY;

export const SESSION_DURATION_MINUTES = 20;
export const SESSION_DURATION_SECONDS =
  SESSION_DURATION_MINUTES * SECONDS_PER_MINUTE;
export const SESSION_DURATION_MS =
  SESSION_DURATION_SECONDS * MILLISECONDS_PER_SECOND;

export const GENERAL_RANKING_CACHE_TTL_SECONDS = 5 * SECONDS_PER_MINUTE;
export const DEFAULT_PAGE = 1;
export const DEFAULT_PAGE_SIZE = 100;
export const MAX_PAGE_SIZE = 1000;

export const RATE_LIMIT_CLEANUP_INTERVAL_MS = 5 * MILLISECONDS_PER_MINUTE;
export const RATE_LIMIT_AUTH_MAX_REQUESTS = 10;
export const RATE_LIMIT_WRITE_MAX_REQUESTS = 30;
export const RATE_LIMIT_READ_MAX_REQUESTS = 100;
export const RATE_LIMIT_UPLOAD_MAX_REQUESTS = 10;

export const DEFAULT_DB_POOL_SIZE = 10;
export const DB_IDLE_TIMEOUT_MS = 30 * MILLISECONDS_PER_SECOND;
export const DB_CONNECTION_TIMEOUT_MS = 10 * MILLISECONDS_PER_SECOND;
